name: Create Release

on:
  repository_dispatch:
    types: [new-build]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Debug event
        run: |
          echo "Triggered!"
          echo "${{ toJson(github.event) }}"

      - name: Get artifact ID
        env:
          TOKEN: ${{ secrets.AC_TOKEN }}
        run: |
          curl -s \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/luktronics-org/aviologic/actions/runs/${{ github.event.client_payload.run_id }}/artifacts \
            > artifacts.json

          cat artifacts.json

          ARTIFACT_ID=$(jq -r '.artifacts[0].id' artifacts.json)
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$ARTIFACT_ID"
          
      - name: Download artifact
        env:
          TOKEN: ${{ secrets.AC_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/luktronics-org/aviologic/actions/artifacts/$ARTIFACT_ID/zip \
            -o artifact.zip

          ls -lh artifact.zip
          

      - name: Unzip
        run: |
          unzip artifact.zip -d artifact

      - name: Generate MD5 checksums
        run: |
          find artifact -type f | while read FILE; do
            md5sum "$FILE" | awk -v fname="$(basename "$FILE")" '{print $1 "  " fname}'
          done > artifact/md5sums.txt
          cat artifact/md5sums.txt

      - name: Create release via API
        env:
          TOKEN: ${{ secrets.AC_TOKEN }}
        run: |
          TAG="${{ github.event.client_payload.tag }}"

          curl -s -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/luktronics-org/aviologic-binaries/releases \
            -d "{
              \"tag_name\": \"$TAG\",
              \"name\": \"$TAG\",
              \"draft\": false,
              \"prerelease\": false
            }"

          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Upload asset
        env:
          TOKEN: ${{ secrets.AC_TOKEN }}
        run: |
          # Get release ID
          RELEASE_ID=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/luktronics-org/aviologic-binaries/releases/tags/$TAG \
            | jq -r '.id')

          echo "Release ID: $RELEASE_ID"

          find artifact -type f | while read FILE; do
            FILENAME=$(basename "$FILE")
            echo "Uploading: $FILENAME"
            curl -s -X POST \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$FILE" \
              "https://uploads.github.com/repos/luktronics-org/aviologic-binaries/releases/$RELEASE_ID/assets?name=$FILENAME"
          done

